### ISSUE TITLE
Google::APIClient::InstalledAppFlow depends on gems in development group

### ISSUE THREAD

**Issue by mynameisbart** [googleapis/google-api-ruby-client#537]
We recently upgraded versions of this gem on our rails 3.2.x app and encountered the following error:

```
$ bundle exec rails c
/data/app/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:317:in `rescue in depend_on': No such file to load -- launchy (LoadError)
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:312:in `depend_on'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:225:in `require_dependency'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/engine.rb:444:in `block (2 levels) in eager_load!'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/engine.rb:443:in `each'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/engine.rb:443:in `block in eager_load!'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/engine.rb:441:in `each'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/engine.rb:441:in `eager_load!'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `instance_exec'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:30:in `run'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `each'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/initializable.rb:54:in `run_initializers'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/application.rb:136:in `initialize!'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /data/app/releases/20170213003937/config/environment.rb:8:in `<top (required)>'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/application.rb:103:in `require_environment!'
	from /data/app/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.17/lib/rails/commands.rb:40:in `<top (required)>'
	from script/rails:12:in `require'
	from script/rails:12:in `<main>'
```

We had to move launchy out of a development bundle group into the default group as development and test gems are included from via `bundle --deployment --without development test`

Should this class actually be in the lib folder and depending on non production gems?

**Comment by dazuma** [comment]
InstalledAppFlow is not nominally part of the library itself. It's a convenience tool for performing an OAuth flow under certain conditions (such as a command line on a GUI terminal). I agree it probably doesn't belong in this gem at all, and indeed it is marked as deprecated, but unfortunately we can't completely remove it without breakage. For now we can put a rescue in the file to prevent the file from loading (but not throw an exception) if launchy is not present.

That said, using `eager_load` on this gem is probably not a good idea anyway because of the sheer size. It's probably having an adverse impact on your startup time and memory usage.
