### ISSUE TITLE
sheet name cannot start with letter and number

### ISSUE THREAD

**Issue by logicminds** [googleapis/google-api-ruby-client#715]
The a1 notation specifies I can use the sheet name as the range (Sheet1 refers to all the cells in Sheet1).  However, if my sheet name starts with a letter and number the api thinks I want column d09037 on sheet1 instead of the sheet name called `d09037`

https://developers.google.com/sheets/api/guides/concepts

```
 data = [
            {
                range: 'd09037',
                values: [[]]
            },
        ]
        buv = Google::Apis::SheetsV4::BatchUpdateValuesRequest.new(
            data: data,
            value_input_option: 'RAW')
        result = service.batch_update_values(spreadsheet_id, buv)
        puts "#{result.total_updated_cells} cells updated."
        result

```

Resulting error

```
error: badRequest: Invalid data[0]: Range (Sheet1!D9037) exceeds grid limits. Max rows: 1000, max columns: 26
Traceback (most recent call last):
	38: from /usr/bin/cb:23:in `<main>'
	37: from /usr/bin/cb:23:in `load'
	36: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/exe/cb:5:in `<top (required)>'
	35: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/gli-2.17.2/lib/gli/app_support.rb:83:in `run'
	34: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/gli-2.17.2/lib/gli/app_support.rb:309:in `call_command'
	33: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/gli-2.17.2/lib/gli/app_support.rb:296:in `block in call_command'
	32: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/gli-2.17.2/lib/gli/command_support.rb:131:in `execute'
	31: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/lib/myapp/cli.rb:256:in `block (3 levels) in initialize_gli'
	30: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/base.rb:134:in `block in event'
	29: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/aasm.rb:121:in `aasm_fire_event'
	28: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/core/event.rb:48:in `fire'
	27: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/core/event.rb:139:in `_fire'
	26: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/core/event.rb:139:in `each'
	25: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/core/event.rb:149:in `block in _fire'
	24: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/core/transition.rb:47:in `execute'
	23: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/core/transition.rb:80:in `invoke_callbacks_compatible_with_guard'
	22: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/aasm-4.12.3/lib/aasm/core/transition.rb:80:in `instance_exec'
	21: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/lib/myapp/client.rb:39:in `block (3 levels) in <class:Client>'
	20: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/lib/myapp/cli.rb:258:in `block (4 levels) in initialize_gli'
	19: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/lib/myapp/commands/rig/inventory.rb:15:in `run'
	18: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/lib/myapp/commands/rig/inventory.rb:29:in `generate_google_report'
	17: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/lib/myapp/exporters/inventory_report.rb:108:in `generate'
	16: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/lib/myapp/exporters/inventory_report.rb:103:in `update_inventory'
	15: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/myapp-0.9.0/lib/myapp/exporters/inventory_report.rb:209:in `batch_update_values'
	14: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/generated/google/apis/sheets_v4/service.rb:602:in `batch_update_values'
	13: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	12: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/lib/google/apis/core/http_command.rb:93:in `execute'
	11: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	10: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 9: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 8: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/lib/google/apis/core/http_command.rb:101:in `block in execute'
	 7: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	 6: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 5: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 4: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
	 3: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/lib/google/apis/core/http_command.rb:299:in `execute_once'
	 2: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/lib/google/apis/core/http_command.rb:183:in `process_response'
	 1: from /opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/lib/google/apis/core/api_command.rb:116:in `check_status'
/opt/myapp/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.8/lib/google/apis/core/http_command.rb:218:in `check_status': badRequest: Invalid data[0]: Range (Sheet1!D9037) exceeds grid limits. Max rows: 1000, max columns: 26 (Google::Apis::ClientError)
```

**Comment by TheRoyalTnetennba** [comment]
I was unable to find a way to do this with only the sheet name for sheet names that start with a letter and number. As a workaround you could do:
```ruby
def number_to_column number_of_columns
  name = 'A'
  (number_of_columns - 1).times { name.succ! }
  name  
end

sheet_name = "d09037"
result = service.get_spreadsheet(spreadsheet_id)
sheet = result.sheets.find { |sheet| sheet.properties.title == sheet_name }
number_of_columns = sheet.properties.grid_properties.column_count
column_name = number_to_column number_of_columns

data = [
  {
      range: "#{sheet_name}!A:#{column_name}",
      values: [(0...number_of_columns).map { 'asdf' }]
  },
]
buv = Google::Apis::SheetsV4::BatchUpdateValuesRequest.new(
  data: data,
  value_input_option: 'RAW')
result = service.batch_update_values(spreadsheet_id, buv)
puts "#{result.total_updated_cells} cells updated."
result
```

**Comment by logicminds** [comment]
Thanks for the suggestion.  I ended up just prepending an underscore to the name `_d09037` when creating and referencing the sheet.
