### ISSUE TITLE
where to put corporate proxy cert?

### ISSUE THREAD

**Issue by radikpsb** [googleapis/google-api-ruby-client#716]
I'm using fastlane supply, which using google api client publishes app to google play.
When I try to publish app I get ssl error.
`SET SSL_CERT_FILE=<path_to_corp_cert/cert.pem>` doesn't help. At the same time I can download ruby gems from https://rubygems.org/ through gem install

Full stacktrace:

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `connect': [!] SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `ssl_connect'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:41:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `create_socket'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
        from C:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from C:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:291:in `execute_once'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:101:in `block in execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:93:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/generated/google/apis/androidpublisher_v2/service.rb:200:in `insert_edit'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/supply/lib/supply/client.rb:92:in `block in begin_edit'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/supply/lib/supply/client.rb:396:in `call_google_api'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/supply/lib/supply/client.rb:92:in `begin_edit'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
        from Fastfile:27:in `block (2 levels) in parsing_binding'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.104.0/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/bin/fastlane:23:in `<main>'
```

**Comment by radikpsb** [comment]
I've added to `%RUBY_PATH%\lib\ruby\gems\2.4.0\gems\httpclient-2.8.3\lib\httpclient\cacert.pem` my organization's certificate and everything works like a charm.
