### ISSUE TITLE
will youtube_analytics_v1 work after Oct 31, 2018

### ISSUE THREAD

**Issue by charliepixegon** [googleapis/google-api-ruby-client#732]
I got the following email and checked out the migration guide but didn't see anything about a new ruby version? Will this library still work after Oct 31, 2018?

=== email ===

To whom it may concern, 

You’re receiving this email because you’ve accessed the YouTube Analytics API service in the last few months. If you have already made the necessary updates, you can ignore this email. If you do not manage API services, please forward this email to the appropriate person for your organization.

On April 26, 2018 we released version 2 (v2) of this service which supports targeted queries and group management for YouTube Analytics data. As a result, we will be sunsetting version 1 (v1) of that service on October 31, 2018. 

Please note that all service requests to v1 will no longer work after that date, preventing you from updating and accessing information. Be sure to upgrade to v2 of this service before October 31, 2018 to avoid any interruption. 

This migration guide provides detailed information about the deprecated features and required code changes.

Best regards,
The YouTube Analytics Team

**Comment by charliepixegon** [comment]
I can confirm that after today I'm now getting this response when trying to make a call to youtube analytics. 

Version 1 of the YouTube Analytics API has been deprecated as of November 1, 2018. Please refer to the migration guide for details about how to update your client to work with version 2 of the API: https://developers.google.com/youtube/analytics/migration.
["/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/lib/google/apis/core/http_command.rb:228:in `check_status'", "/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/lib/google/apis/core/api_command.rb:116:in `check_status'", "/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/lib/google/apis/core/http_command.rb:193:in `process_response'", "/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/lib/google/apis/core/http_command.rb:309:in `execute_once'", "/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'", "/usr/local/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'", "/usr/local/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'", "/usr/local/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'", "/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/lib/google/apis/core/http_command.rb:110:in `block in execute'", "/usr/local/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'", "/usr/local/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'", "/usr/local/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'", "/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/lib/google/apis/core/http_command.rb:102:in `execute'", "/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'", "/usr/local/lib/ruby/gems/2.5.0/gems/google-api-client-0.25.0/generated/google/apis/youtube_analytics_v1/service.rb:460:in `query_report'", "MCNGetVideoViewsByDay.rb:119:in `block in <main>'", "MCNGetVideoViewsByDay.rb:99:in `each'", "MCNGetVideoViewsByDay.rb:99:in `<main>'"]
Started at 2018-11-27 21:06:11 -0500 Ended at 2018-11-27 21:06:11 -0500
