### ISSUE TITLE
Compute Engine API - required: Required field 'resource' not specified

### ISSUE THREAD

**Issue by kgaikwad** [googleapis/google-api-ruby-client#754]
Here in [classes.rb](https://github.com/googleapis/google-api-ruby-client/blob/master/generated/google/apis/compute_v1/classes.rb), under Instance class I can see [initialize](https://github.com/googleapis/google-api-ruby-client/blob/master/generated/google/apis/compute_v1/classes.rb#L7279) constructor which accepts arguments.

If I tried to create instance using below code:
> instance1 = Google::Apis::ComputeV1::Instance.new(data) # here data contains all required attributes 
service.insert_instance(@project, zone, instance1)

giving me error - 
`ArgumentError: wrong number of arguments (given 1, expected 0) on line /generated/google/apis/compute_v1/classes.rb at initialize`

If I assigned each attribute after initializing instance1 object then it creates instance. i.e no argument to .new method. Even I tried calling `update!` method on `instance1` object still giving same error.

When I verified in google cloud [document](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert), I found that under Examples -> ruby section, it says:

>  TODO: Assign values to desired members of `request_body`:
request_body = Google::Apis::ComputeV1::Instance.new

i.e without arguments to .new method and mentioned to assign values using request_body object.

Please let me know which way is appropriate to create instance and why it is giving error "Wrong arguments" as method definitions mentioned arguments.

If assigning attributes after `Instance` object initialization then there is issue in `generated/google/apis/compute_v1/classes.rb`. 

**EDIT:**
Able to resolve above issue. Now I am getting below error -
"**required: Required field 'resource' not specified**"
google-api-client-0.23.9/lib/google/apis/core/http_command.rb:218:in `check_status', 
google-api-client-0.23.9/lib/google/apis/core/api_command.rb:116:in `check_status', "google-api-client-0.23.9/lib/google/apis/core/http_command.rb:183:in `process_response', google-api-client-0.23.9/lib/google/apis/core/http_command.rb:300:in `execute_once',
google-api-client-0.23.9/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'

**Comment by kgaikwad** [comment]
I was able to resolve this issue. Corrected required attributes.
