### ISSUE TITLE
time_min and time_max type documentation is misleading

### ISSUE THREAD

**Issue by afeld** [googleapis/google-api-ruby-client#755]
#### Environment details

  - OS: MacOS 10.14.2
  - Ruby version: 2.5.0
  - Gem name and version: google-api-client (0.27.3)

#### Steps to reproduce

```
$ ruby my_script.rb
...
Traceback (most recent call last):
	10: from my_script.rb:64:in `<main>'
	 9: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.27.3/generated/google/apis/calendar_v3/service.rb:1412:in `list_events'
	 8: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.27.3/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	 7: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.27.3/lib/google/apis/core/http_command.rb:99:in `execute'
	 6: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.27.3/lib/google/apis/core/api_command.rb:67:in `prepare!'
	 5: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.27.3/lib/google/apis/core/http_command.rb:159:in `prepare!'
	 4: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1698:in `query_values='
	 3: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1698:in `each'
	 2: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1712:in `block in query_values='
	 1: from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:360:in `encode_component'
/Users/aidan/.rvm/gems/ruby-2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:370:in `rescue in encode_component': Can't convert DateTime into String. (TypeError)
```

#### Code example

```ruby
response = service.list_events(
  calendar_id,
  time_min: DateTime.now
)
```

---

[`#list_events`](https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/CalendarV3/CalendarService#list_events-instance_method) (and presumably other methods) say in the documentation that they accept a `DateTime`, when in fact they want an "RFC3339 timestamp with mandatory time zone offset" as a String.

/cc https://github.com/gsuitedevs/ruby-samples/pull/19

**Comment by blowmage** [comment]
Yeah, the value to use should be a `Time` instance, not a `DateTime` instance.

**Comment by dazuma** [comment]
It is supposed to accept either form (`DateTime` object or String). The `DateTime` support regressed at some point (probably when the library migrated away from hurley). Working on a fix.
