### ISSUE TITLE
NoMethodError: undefined method `status' for nil:NilClass

### ISSUE THREAD

**Issue by igorpeshansky** [googleapis/google-api-ruby-client#764]
OS: Debian stretch
Ruby version: 2.4.0
Gem name and version: google-api-client-0.23.9

The following code (in `foo.rb`) raises a NoMethodError when using an incorrect `http_proxy` setting:
```ruby
require 'google/apis'
require 'google/apis/logging_v2'

client = Google::Apis::LoggingV2::LoggingService.new
client.authorization = Google::Auth.get_application_default('https://www.googleapis.com/auth/logging.write')
client.authorization.fetch_access_token!

client.write_entry_log_entries(
  Google::Apis::LoggingV2::WriteLogEntriesRequest.new(
    entries: [
      Google::Apis::LoggingV2::LogEntry.new(
        severity: 0,
        timestamp: {seconds: 1550166287, nanos: 0},
        text_payload: 'my test log'
      )
    ],
    log_name: 'my_log',
    resource: {type: 'global'},
    labels: {},
    partial_success: true
  ),
  options: { api_format_version: '2' }
)
```

I was using the `google-fluentd` installation, because it already contains all of the necessary gems, but it will likely produce the same error in a pristine environment as well.

Running the above code (`/opt/google-fluentd/embedded/bin/ruby foo.rb`) produces:
```
/opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:264:in `error': undefined method `status' for nil:NilClass (NoMethodError)
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:303:in `rescue in execute_once'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:286:in `execute_once'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:101:in `block in execute'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:93:in `execute'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
        from /opt/google-fluentd/embedded/lib/ruby/gems/2.4.0/gems/google-api-client-0.23.9/generated/google/apis/logging_v2/service.rb:691:in `write_entry_log_entries'
        from foo.rb:8:in `<main>'
```

I suspect this is coming from the unchecked access to `res` [here](https://github.com/googleapis/google-api-ruby-client/blob/master/lib/google/apis/core/http_command.rb#L274) (looks like in the case of a failed proxy connection, `res` is `Nil`).

**Comment by blowmage** [comment]
Can you update the code example showing how you are setting an "incorrect `http_proxy` setting"?

**Comment by igorpeshansky** [comment]
Hi. So I've used [these instructions](https://github.com/salrashid123/gcpsamples/tree/master/proxy) to set up a proxy with basic authentication (which defaults to user `user1` with password `user1`), and then set `http_proxy='http://user1:wrong@localhost:3128'` (I've also tried `http_proxy='http://invalid:wrong@localhost:3128'`). This caused the proxy to issue a 407.

**Comment by blowmage** [comment]
Ah, okay. So if I am understanding you correctly, you intentionally set a bad proxy to see how it behaved? And the error you got was unexpected, correct?

**Comment by igorpeshansky** [comment]
Correct. The bug is that a transmission error (which ought to be retried) is masked by an internal code error that definitely won't be.

**Comment by blowmage** [comment]
@igorpeshansky Thanks for the bug report!

@TheRoyalTnetennba Do you know when the next gem release will be?
