### ISSUE TITLE
Signet::AuthorizationError: Unexpected error: #<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>

### ISSUE THREAD

**Issue by illustrarium** [googleapis/google-api-ruby-client#830]
#### Environment details

  - Ubuntu 16.04:
  - 2.4.0:
  - gem 'google-api-client', '~> 0.11':

#### Steps to reproduce

Until 09/14 my code works fine, but last 2 week I can't writing in SpreadSheet from production server and getting following:
```
Signet::AuthorizationError: Unexpected error: #<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>
  from /home/deploy/s/shared/bundle/ruby/2.4.0/gems/googleauth-0.9.0/lib/googleauth/signet.rb:116:in 'rescue in retry_with_error'
  from /home/deploy/s/shared/bundle/ruby/2.4.0/gems/googleauth-0.9.0/lib/googleauth/signet.rb:105:in 'retry_with_error'
  from /home/deploy/s/shared/bundle/ruby/2.4.0/gems/googleauth-0.9.0/lib/googleauth/signet.rb:79:in 'fetch_access_token!'
  from /home/deploy/s/releases/20190923113936/app/services/googlespreadsheets.rb:54:in 'append'
  from (irb):1
  from /home/deploy/s/shared/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in 'start'
  from /home/deploy/s/shared/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in 'start'
  from /home/deploy/s/shared/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in 'console'
  from /home/deploy/s/shared/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in 'run_command!'
  from /home/deploy/s/shared/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands.rb:18:in '<top (required)>'
  from bin/rails:9:in 'require'
  from bin/rails:9:in '<main>'

```
Looks like i can't use fetch_access_token anymore. What's I'm do wrong? This code works fine from development server. Only two differences between it: dev server location in Belarus, production in Russia.

#### Code example

```ruby
def append
    service = Google::Apis::SheetsV4::SheetsService.new

    scope = 'https://www.googleapis.com/auth/spreadsheets'

    service.authorization = Google::Auth::ServiceAccountCredentials.make_creds(
    json_key_io: File.open(Rails.root + "KEY.json"),
    scope: scope)

    service.authorization.fetch_access_token!


    spreadsheet_id = ENV['SPREADSHEET_ID']  # TODO: Update placeholder value.

    # The A1 notation of the values to clear.
    range = 'A2:K'  # TODO: Update placeholder value.

    # TODO: Assign values to desired members of `request_body`:
    request_body = Google::Apis::SheetsV4::ClearValuesRequest.new

    response = service.clear_values(spreadsheet_id, range, request_body)

    # range = 'A2:K'  # TODO: Update placeholder value.
    orders = Order.where(customer_id: 3814)
    values = []

    orders.each do |order|
      v = [order.reserved, order.id, status_text(order.status), order.title, order.corner.name, order.width, order.lenght, order.spinka, order.seats, order.kings, order.pillows, order.ldsp]
      values << v
    end


    # TODO: Assign values to desired members of `request_body`:
    request_body = Google::Apis::SheetsV4::ValueRange.new(range: range,
                                                          values: values)
    value_input_option = "RAW"

    response = service.append_spreadsheet_value(spreadsheet_id, range, request_body, value_input_option: value_input_option)

    # TODO: Change code below to process the `response` object:
    return response.to_json
  end
```

**Comment by illustrarium** [comment]
Problem was linked with free proxy server thath blocked all my requests exept to telegram servers.

**Comment by snex** [comment]
I am having this same problem and I am not using any proxies.

**Comment by illustrarium** [comment]
> I am having this same problem and I am not using any proxies.

check if your server with ruby app have access to google servers?
