### ISSUE TITLE
OpenCensus raises errors when HttpCommand#execute used in existing trace

### ISSUE THREAD

**Issue by danielmbarlow** [googleapis/google-api-ruby-client#850]
We have a support contract with Google, but I have been asked to create the issue here 

#### Environment details

  - OS: Linux
  - Ruby version: 2.6.4
  - Gem name and version: google-api-ruby-client

#### Steps to reproduce

  1. Create an OpenCensus root trace using `OpenCensus::Trace#in_span` for example, in the [OpenCensus rack integration.](https://github.com/census-instrumentation/opencensus-ruby/blob/8cb9771b218e440e825c99981ea405d40f735926/lib/opencensus/trace/integrations/rack_middleware.rb#L80)
  2. Call `Google::Apis::Core::HttpCommand#execute`, perhaps using [Google::Cloud::Storage::Bucket#create_file](http://blowmage.com/google-cloud-ruby/docs/google-cloud-storage/v1.7.0/Google/Cloud/Storage/Bucket.html#create_file-instance_method) as we do in our application.

#### Code example

It might also be possible to replicate this behaviour by including a second call to `#execute` [in this test](https://github.com/googleapis/google-api-ruby-client/blob/4e38887c1f69f7527648fe572f708ad2b48a2a96/spec/google/apis/core/http_command_spec.rb#L337), but I haven't tried that.

#### Other information
Perhaps the fix could be to do use `OpenCensus::Trace.in_span` which would allow OpenCensus to handle it's own context. I had a think about how to do this, as you can see below:

```
def execute(client)
  prepare!

  with_opencensus_span do
    begin
      #   Retriable.retriable tries: options.retries + 1,
      # ...
      # ensure
      #   @http_res = nil
      #   release!
    end
  end
end

def with_opencensus_span
  return yield unless opencensus_available?

  OpenCensus::Trace.in_span url.path.to_s do |span|
    begin
      opencensus_begin_span(span)

      yield
    ensure
      opencensus_end_span(span)
    end
  end
end

def opencensus_begin_span(span)
  span.put_attribute "http.host", url.host.to_s
  span.put_attribute "http.method", method.to_s.upcase
  span.put_attribute "http.path", url.path.to_s
  if body.respond_to? :bytesize
    span.put_message_event \
             OpenCensus::Trace::SpanBuilder::SENT, 1, body.bytesize
  end

  formatter = OpenCensus::Trace.config.http_formatter
  if formatter.respond_to? :header_name
    header[formatter.header_name] = formatter.serialize span.context.trace_context
  end
rescue StandardError => e
  # Log exceptions and continue, so opencensus failures don't cause
  # the entire request to fail.
  logger.debug { sprintf('Error opening OpenCensus span: %s', e) }
end

def opencensus_available?
  return false unless OPENCENSUS_AVAILABLE && options.use_opencensus
  # Still need to figure out how to do this
  return false if @opencensus_span
  return false unless OpenCensus::Trace.span_context

  true
end

# Never gets called unless opencensus is available
def opencensus_end_span(span)
  if @http_res.body.respond_to? :bytesize
    span.put_message_event \
              OpenCensus::Trace::SpanBuilder::RECEIVED, 1, @http_res.body.bytesize
  end
  status = @http_res.status.to_i
  if status > 0
    span.set_status map_http_status status
    span.put_attribute "http.status_code", status
  end

  # no longer necessary
  # OpenCensus::Trace.end_span span
  span = nil
rescue StandardError => e
  # Log exceptions and continue, so failures don't cause leaks by
  # aborting cleanup.
  logger.debug { sprintf('Error finishing OpenCensus span: %s', e) }
end
```

**Comment by dazuma** [comment]
Can you post the actual error you get, along with a (suitably redacted) stack trace? I'm having some trouble reproducing this.

**Comment by danielmbarlow** [comment]
OK will probably be early next week before I can do that.

**Comment by danielmbarlow** [comment]
@dazuma Here it is:

```
developer:/app$ bundle exec ruby create_error.rb
Traceback (most recent call last):
        4: from create_error.rb:5:in `<main>'
        3: from /usr/local/bundle/bundler/gems/opencensus-ruby-300a33a7129f/lib/opencensus/trace.rb:104:in `start_request_trace'
        2: from create_error.rb:6:in `block in <main>'
        1: from /usr/local/bundle/bundler/gems/opencensus-ruby-300a33a7129f/lib/opencensus/trace.rb:186:in `in_span'
/usr/local/bundle/bundler/gems/opencensus-ruby-300a33a7129f/lib/opencensus/trace.rb:202:in `end_span': The given span doesn't match the currently active span (RuntimeError)
```

In our Gemfile:
```
...
gem "google-cloud-storage", "~> 1.18.2", require: "google/cloud/storage"
gem "opencensus", "~> 0.4.0"
...
```

The script I used to create the error:
```
require "google/cloud/storage"

# If you set this to false, there's no error
Google::Apis::RequestOptions.default.use_opencensus = true

# I copied these out of the OpenCensus Rack middleware, which is the context
# of the error in our project.
OpenCensus::Trace.start_request_trace(same_process_as_parent: false) do |span_context|
  OpenCensus::Trace.in_span("test-span") do |span|
    storage = Google::Cloud::Storage.new(
      project_id: ENV.fetch("GCP_PROJECT_ID"),
      credentials: JSON.parse(ENV.fetch("GCS_SERVICE_ACCOUNT_KEY"))
    )

    bucket = storage.bucket "test-bucket"

    # The exception should happen here
    bucket.create_file "test.txt"
  end
end
```

**Comment by dazuma** [comment]
Thanks much for the small repro script! It helped narrow the issue down substantially. Looks like the issue happens specifically when an upload call is done, due to the way the upload call reports its results internally. I have a PR pending with a fix. We're going into a release freeze for the Thanksgiving holiday in the U.S., but we'll release the fix at the beginning of next week.

**Comment by danielmbarlow** [comment]
Thanks @dazuma
