### ISSUE TITLE
Faraday::SSLError certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by AlexWayfer** [googleapis/google-api-ruby-client#893]
```
`connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:932:in `start'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:152:in `request_via_request_method'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:137:in `request_with_wrapped_block'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:128:in `perform_request'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:70:in `block in call'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter.rb:60:in `connection'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:68:in `call'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/request/url_encoded.rb:25:in `call'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/signet-0.14.0/lib/signet/oauth_2/client.rb:1020:in `fetch_access_token'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/signet-0.14.0/lib/signet/oauth_2/client.rb:1054:in `fetch_access_token!'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/googleauth-0.13.0/lib/googleauth/signet.rb:81:in `block in fetch_access_token!'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/googleauth-0.13.0/lib/googleauth/signet.rb:108:in `retry_with_error'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/googleauth-0.13.0/lib/googleauth/signet.rb:80:in `fetch_access_token!'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/googleauth-0.13.0/lib/googleauth/signet.rb:52:in `apply!'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/google-api-client-0.42.1/lib/google/apis/core/http_command.rb:323:in `apply_request_options'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/google-api-client-0.42.1/lib/google/apis/core/http_command.rb:299:in `execute_once'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/google-api-client-0.42.1/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/google-api-client-0.42.1/lib/google/apis/core/http_command.rb:110:in `block in execute'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/google-api-client-0.42.1/lib/google/apis/core/http_command.rb:102:in `execute'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/google-api-client-0.42.1/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
Jul 21 22:39:34 stream-assistant-bot rbenv[26273]:         from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/google-api-client-0.42.1/generated/google/apis/youtube_v3/service.rb:828:in `list_channels'
````

### Environment details

  - OS: Debian 10 (server on Hetzner)
  - Ruby version: 2.7.1 (installed via `rbenv` and `ruby-build`)
  - Gem name and version: `google-api-client-0.42.1`

#### Steps to reproduce

  1. Make a request.

#### Code example

```ruby
list_channels('snippet,contentDetails', mine: true)
```

**Comment by AlexWayfer** [comment]
I can't reproduce it locally, so it's something environment-related, and I don't know what and how to know. I have not done something unusual.

**Comment by AlexWayfer** [comment]
Debug logs:

```
[13] pry(main)> @youtube_service.list_channels('snippet,contentDetails', mine: true)
D, [2020-07-24T11:06:00.403853 #11895] DEBUG -- : Sending HTTP get https://www.googleapis.com/youtube/v3/channels?mine=true&part=snippet%2CcontentDetails
D, [2020-07-24T11:06:20.482292 #11895] DEBUG -- : Caught error Unexpected error: #<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>>
D, [2020-07-24T11:06:20.482438 #11895] DEBUG -- : Error - #<Signet::AuthorizationError: Unexpected error: #<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>>>

D, [2020-07-24T11:06:20.482568 #11895] DEBUG -- : Retrying after authentication failure
D, [2020-07-24T11:06:21.022592 #11895] DEBUG -- : Sending HTTP get https://www.googleapis.com/youtube/v3/channels?mine=true&part=snippet%2CcontentDetails
D, [2020-07-24T11:06:25.697831 #11895] DEBUG -- : Caught error Unexpected error: #<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>>
D, [2020-07-24T11:06:25.697999 #11895] DEBUG -- : Error - #<Signet::AuthorizationError: Unexpected error: #<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>>>

D, [2020-07-24T11:06:25.698203 #11895] DEBUG -- : Retrying after authentication failure
Signet::AuthorizationError: Unexpected error: #<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>>
from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/googleauth-0.13.0/lib/googleauth/signet.rb:118:in `rescue in retry_with_error'
Caused by Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
Caused by OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
from /home/stream_assistant/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
```

**Comment by AlexWayfer** [comment]
Reproducible with `curl`, some googling and… finally it has been resolved via `apt install ca-certificates`. Sorry for bothering you. I thought there need be some system package with certificates, but I didn't know which one specifically, and I didn't believe it was not installed by default or with other packages during setup.
