### ISSUE TITLE
#cancel_purchase_subscription doesn't work at v0.46.1

### ISSUE THREAD

**Issue by mizoR** [googleapis/google-api-ruby-client#913]
Backward compatibility for `#cancel_purchase_subscription` has been broken since v0.46.1.
see: https://github.com/googleapis/google-api-ruby-client/compare/0.46.0...0.46.1#diff-3539c0900aa42a29d1e11f430cc57363631b7873ebe3ba32a2fc18f871e7a7d1

Also the api got "Invalid Request" even if the arguments are fixed with my app side.

As far as I quick checked [the API document - cancel_purchase_subscriotion](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions/cancel?hl=ja), v0.46.0 will be correct.

#### Environment details

  - OS: Linux
  - Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]
  - Gem name and version: google-api-client (0.46.1)

#### Steps to reproduce

  1. Run code example => ArgumentError

#### Code example

```ruby
require 'google/apis/androidpublisher_v3'

package_id = ENV.fetch('GOOGLE_PACKAGE_ID')
product_id = ENV.fetch('GOOGLE_PRODUCT_ID')
token      = ENV.fetch('GOOGLE_TOKEN')

Androidpublisher = Google::Apis::AndroidpublisherV3

scope = ['https://www.googleapis.com/auth/androidpublisher']
authorization = Google::Auth.get_application_default(scope)

service = Androidpublisher::AndroidPublisherService.new.tap do |service|
  service.authorization = authorization
  service.request_options.retries = 5
end

service.cancel_purchase_subscription(package_id, product_id, token)
```

```
Traceback (most recent call last):
        1: from foo.rb:17:in `<main>'
/usr/local/bundle/gems/google-api-client-0.46.1/generated/google/apis/androidpublisher_v3/service.rb:1885:in `cancel_purchase_subscription': wrong number of arguments (given 3, expected 2) (ArgumentError)
```

Thanks!

**Comment by mizoR** [comment]
This problem seems to have been fixed in v0.46.2. I don't know why generator didn't work with v0.46.1  properly though 🤔 

Anyway, thanks!
